/* Generated by re2c 0.14.3 on Mon Nov 19 05:15:35 2018 */
#line 1 "number.l"
#include <stdio.h>

enum num_t { ERR, BIN, OCT, DEC, HEX };

static int lex(const char *YYCURSOR)
{
    const char *YYMARKER;
    
#line 12 "number.c"
{
	char yych;

	yych = *YYCURSOR;
	switch (yych) {
	case '0':	goto yy4;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy5;
	default:	goto yy2;
	}
yy2:
	++YYCURSOR;
yy3:
#line 18 "number.l"
	{ return ERR; }
#line 35 "number.c"
yy4:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:	goto yy14;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy12;
	case 'B':
	case 'b':	goto yy16;
	case 'X':
	case 'x':	goto yy11;
	default:	goto yy3;
	}
yy5:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:	goto yy9;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy6;
	default:	goto yy3;
	}
yy6:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy9;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy6;
	default:	goto yy8;
	}
yy8:
	YYCURSOR = YYMARKER;
	goto yy3;
yy9:
	++YYCURSOR;
#line 21 "number.l"
	{ return DEC; }
#line 94 "number.c"
yy11:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy8;
	goto yy22;
yy12:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy14;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy12;
	default:	goto yy8;
	}
yy14:
	++YYCURSOR;
#line 20 "number.l"
	{ return OCT; }
#line 118 "number.c"
yy16:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy8;
	goto yy18;
yy17:
	++YYCURSOR;
	yych = *YYCURSOR;
yy18:
	switch (yych) {
	case 0x00:	goto yy19;
	case '0':
	case '1':	goto yy17;
	default:	goto yy8;
	}
yy19:
	++YYCURSOR;
#line 19 "number.l"
	{ return BIN; }
#line 137 "number.c"
yy21:
	++YYCURSOR;
	yych = *YYCURSOR;
yy22:
	switch (yych) {
	case 0x00:	goto yy23;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy21;
	default:	goto yy8;
	}
yy23:
	++YYCURSOR;
#line 22 "number.l"
	{ return HEX; }
#line 172 "number.c"
}
#line 23 "number.l"

}

int main(int argc, char **argv)
{int i = 1;
    for (; i < argc; ++i) {
        switch (lex(argv[i])) {
            case ERR: printf("error\n"); break;
            case BIN: printf("binary\n"); break;
            case OCT: printf("octal\n"); break;
            case DEC: printf("decimal\n"); break;
            case HEX: printf("hexadecimal\n"); break;
        }
    }
    return 0;
}